### ISSUE TITLE
Any chance of this being updated to ruby 2.0?

### ISSUE THREAD

**Issue by Nsheppard01** [diginc/BonesPlusPlus#1]
This project hasn't been updated in 4 years. Is it dead? I miss bones, it was the best dicebot, but it's not compatable with the latest version of ruby.

**Comment by diginc** [comment]
I'm not very well suited to the task since ruby is not my strongest language and I've never delt with ruby version differences, but the source is here for anyone to work on however they want.  

I tried to document the installation procedure (and requirements) better than it originally was when I got permission to upload this code from the original author 4 years ago: 

Take a look at https://github.com/diginc/BonesPlusPlus/blob/master/INSTALL

It should be possible to install 1.8 along side your existing ruby installations with https://rvm.io/
